"""Add image_url and limit all fields

Revision ID: f0dbe514fbb4
Revises: b3631ada3c4f
Create Date: 2025-12-30 12:12:41.303707

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f0dbe514fbb4"
down_revision: Union[str, Sequence[str], None] = "b3631ada3c4f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("recipe_ingredient_association")
    op.drop_index(op.f("ix_ingredients_name"), table_name="ingredients")
    op.drop_table("ingredients")
    op.add_column(
        "recipes", sa.Column("image_url", sa.String(length=512), nullable=True)
    )
    op.alter_column(
        "recipes",
        "title",
        existing_type=sa.VARCHAR(length=100),
        type_=sa.String(length=255),
        existing_nullable=False,
    )
    op.alter_column(
        "recipes",
        "instructions",
        existing_type=sa.TEXT(),
        type_=sa.String(length=50000),
        existing_nullable=False,
    )
    op.drop_index(
        op.f("ix_recipes_ingredients_jsonb"),
        table_name="recipes",
        postgresql_using="gin",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_recipes_ingredients_jsonb"),
        "recipes",
        ["ingredients"],
        unique=False,
        postgresql_using="gin",
    )
    op.alter_column(
        "recipes",
        "instructions",
        existing_type=sa.String(length=50000),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.alter_column(
        "recipes",
        "title",
        existing_type=sa.String(length=255),
        type_=sa.VARCHAR(length=100),
        existing_nullable=False,
    )
    op.drop_column("recipes", "image_url")
    op.create_table(
        "ingredients",
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text("nextval('ingredients_id_seq'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("name", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name="ingredients_pkey"),
        postgresql_ignore_search_path=False,
    )
    op.create_index(op.f("ix_ingredients_name"), "ingredients", ["name"], unique=True)
    op.create_table(
        "recipe_ingredient_association",
        sa.Column("recipe_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("ingredient_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["ingredient_id"],
            ["ingredients.id"],
            name=op.f("recipe_ingredient_association_ingredient_id_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["recipe_id"],
            ["recipes.id"],
            name=op.f("recipe_ingredient_association_recipe_id_fkey"),
        ),
        sa.PrimaryKeyConstraint(
            "recipe_id",
            "ingredient_id",
            name=op.f("recipe_ingredient_association_pkey"),
        ),
    )
    # ### end Alembic commands ###
